server:
  port: 8080

spring:
  application:
    name: todolist
  datasource:
    url: jdbc:mysql://localhost:3306/todolist_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

ai:
  base-url: "https://open.bigmodel.cn/api/paas/v4/"
  api-key: ""
  model: "glm-4.7"
  timeout-ms: 30000
